### ISSUE TITLE
Insert a table here please and thank you :)

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#100]
Can you insert the table in the file in this section before the image? The file can be loaded into https://www.tablesgenerator.com/
[MOITable.zip](https://github.com/user-attachments/files/17175805/MOITable.zip)

https://github.com/IllinoisRef/mechref/blob/774da2e3176e83b57b7e9ebc0ce3ae011f86e043/src/pages/sol/bending.astro#L183

**Comment by jcrayb** [comment]
Done!

**Comment by mrhoyle2** [comment]
The table inserted isn't the correct one. The area moment of inerta column should have 3 sub columns

**Comment by jcrayb** [comment]
My bad, I looked at the first column and assumed they were the same.
