### ISSUE TITLE
Search bar not quite working?

### ISSUE THREAD

**Issue by kelliehalloran** [IllinoisRef/mechref#102]
Hi, 

I tried to search for moment of inertia in the statics page and the search bar can't find anything, even though there's a moment of inertia page. The same thing happens with solid mechanics - It's only finding "inertia" in the dynamics page and not statics or solid mechanics. Not sure if that's a problem on my end or if it's a setting that needs to be changed / updated behind the scenes - wanted to flag it just in case!

**Comment by jcrayb** [comment]
To avoid confusion for the students they can only search pages that are deemed completed, but I think that list has not been updated in a week.
