### ISSUE TITLE
New Statics "Frames and Machines" page 

### ISSUE THREAD

**Issue by kelliehalloran** [IllinoisRef/mechref#105]
We're trying to add a "Frames and Machine" page to the statics references, and I tried to copy the "Truss" page, but I think there's some background stuff I need to create that I'm not aware of. @jcrayb would you be able to make a blank page called "Frames and Machines" right after trusses in the Statics page and we can populate it from there? 

Thank you so much!!

**Comment by jcrayb** [comment]
Done!
