### ISSUE TITLE
Remove the expandable feature

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#116]
https://github.com/IllinoisRef/mechref/blob/49e7ab4e5ec822c8b1d85e27092f8e6b2d507eaa/src/pages/sol/stress_transformation.astro#L74C1-L74C125

This warning doesn't need an expansion section. Is there a way to remove it?

**Comment by jcrayb** [comment]
Added this feature. If you add `remove_button="true"` to your Warning element it'll remove the + button.
