### ISSUE TITLE
210 Internal forces/Shear force & bending moment diagrams

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#117]
Can we change the internal forces text in the navitation to match the page title. Also, can we change the name of the page in github to match as well? 

![image](https://github.com/user-attachments/assets/13fdad3c-e26c-4e9f-bc0d-8a396fa14aab)

**Comment by jcrayb** [comment]
We can change the title in the navtree, but changing the name in GH might be a little tougher. We'd have to scout very diligently because otherwise a lot of cross-links and features relying on file names might break.

**Comment by jcrayb** [comment]
Nevermind, it was surprisingly easy. Thankfully VS Code has a "replace across all files" feature.
