### ISSUE TITLE
Sub section vs sub sub section font differences

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#118]
Can we make the visual distiction between sub section and sub sub section more apparent than just font size? Maybe a dark gray for the sub sub sections instead of black? It si currently very hard to tell the difference since they're not always right next to eachother like section and the first sub section are.

**Comment by jcrayb** [comment]
I used the same color scheme as the sidebar, so it gets progressively lighter from Section -> Subsection -> Subsubsection, etc. Let me know if you think it's too big of a difference.

**Comment by mrhoyle2** [comment]
It looks good! Thank you!
