### ISSUE TITLE
about student page updates

### ISSUE THREAD

**Issue by mekersh** [IllinoisRef/mechref#125]
Not sure where my error is but the second sub-section of this page

https://github.com/IllinoisRef/mechref/blob/main/src/pages/about/students.astro

does not seem to be working.  Also not sure what I need to do to make sub-menu items appear in the nav bar on the left (the drop down nav bar) under "Current page".

**Comment by mekersh** [comment]
This is the code section that doesn't seem to work when I put it in the about "for students" page


<SubSection title="In-page features">
        <Row>
            <Col values="6 md-8 lg-9">
                <p>
                    You can also find a in-page navigation menu, showing you all the sections and subsections in the page, and allow you to navigate to them in one click. On phones and tablets, this is located at the top of the page, and on desktops and laptops it is below the sidebar menu.
                </p>
            </Col>
            <Col values="6 md-4 lg-3">
                <img src="/light-menu.png" class="w-100" id="menu-demo"/>

                <script>
                    if (theme == 'dark'){
                        document.querySelector("#menu-demo").src = "/dark-menu.png"
                    }
                </script>
            </Col>
        </Row>      
</SubSection>

**Comment by jcrayb** [comment]
Don't mind that piece of code. It was for the old menu, and it's trying to update the link to an image that doesn't exist anymore.
