### ISSUE TITLE
Dynamics animations broken 

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#19]
The dynamics animations are broken.

**Comment by jcrayb** [comment]
I get "Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state." The error occurs on when it tries to draw text out, on a .drawImage() call in PrairieDraw.js. I also get a bunch of 404s for some random string img files. Will open branch and work on it ASAP.

**Comment by jcrayb** [comment]
So issue was related to text. In dev, when calling for text files (e.g. '/dyn/text/1.png'), the file is fetched at $PWD/file. However, when compiled, the site now is trying to find the file at /public/$PAGE/file (e.g. '/public/dyn/vectors/1.png'). Made script that looks at logs, gets all 404s, and copies the corresponding files into the correct dir.
