### ISSUE TITLE
Figure caption removal

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#21]
Is there a way to batch edit how figures are formatted to remove all of the captions or do I need to do something for each line of code?
https://github.com/IllinoisRef/mechref/blob/a614c9c08b33e77b72a3e983976858635584b284/src/pages/sol/stress.astro#L52C1-L53C1

**Comment by mrhoyle2** [comment]
There are a few in 251 that I would like to keep the captions on for, so having the option to add a caption is prefered.

**Comment by mrhoyle2** [comment]
When you hover over the caption (underlined part), Fig: caption or Fig: name.png comes up. Is there a way to remove this? 

![Screenshot 2024-08-22 105736](https://github.com/user-attachments/assets/c6d83b7d-7dfb-4549-84dd-9e06e707d55d)

**Comment by jcrayb** [comment]
Yes, this was just a dev feature, it is easily removable. I'll take care of that.
