### ISSUE TITLE
# three letter codes

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#22]
Are we keeping the # three letter codes (#sts-ans in the permalink) in these pages? If not is there a way to batch edit the formatting to remove all of them?
https://github.com/IllinoisRef/mechref/blob/a614c9c08b33e77b72a3e983976858635584b284/src/pages/sol/stress.astro#L56C1-L56C123

**Comment by mrhoyle2** [comment]
Ahhh gotcha. Is there a way to have them not appear on the website? Also, I think a standardized naming scheme is a good idea.
Assuming the ID system is easy enough, I think a clear understanding of how/when to use them could be useful for Melany and I to know so you don't have to go back through every time we add things to a page to put the IDs in.

**Comment by jcrayb** [comment]
Yes they can easily be turned off.
