### ISSUE TITLE
Link to other page

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#29]
Add a link to the stress transformation page. (Lower priority) https://github.com/IllinoisRef/mechref/blob/a614c9c08b33e77b72a3e983976858635584b284/src/pages/sol/stress.astro#L124

**Comment by jcrayb** [comment]
Any particular section you want to link to or just the entire "Stress Transformation" page?

**Comment by mrhoyle2** [comment]
No particular section

**Comment by jcrayb** [comment]
I added a sentence with a link telling students to learn more on the Stress Transformation page, let me know if it looks good.
