### ISSUE TITLE
Page navigation sub sub section color change

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#68]
I like that the sub sections and sub sub sections have different colors in the navigation tree, but the light grey is hard to read on the white background. Can we change this to a darker gray while keeping the two levels different colors?
![image](https://github.com/user-attachments/assets/6559f9a8-c333-4d33-88aa-c323f4de0f8d)

**Comment by jcrayb** [comment]
![image](https://github.com/user-attachments/assets/42232b6d-3444-4a0f-86bb-0d1ee697918e)
Does this look more appropriate?

**Comment by mrhoyle2** [comment]
Much better!!
