### ISSUE TITLE
Bouncing derivation??????

### ISSUE THREAD

**Issue by mrhoyle2** [IllinoisRef/mechref#84]
https://github.com/user-attachments/assets/8e463fe6-57fc-4c38-9da2-339bfca52f26

I'm not entirely sure how I maganged do to this. I've checked the code against one's that are working and I cannot figure out what I did wrong. 

https://github.com/IllinoisRef/mechref/blob/cca61dd1fc1f8cb3b6efbdf20e58d59397351f6c/src/pages/sol/axial_loading.astro#L68C1-L74C19

**Comment by mwest1066** [comment]
Hahaha, that's too funny 😂. Hopefully @jcrayb can stop the bouncing!

**Comment by jcrayb** [comment]
Yeah it's just a missing id. I got it!
