### ISSUE TITLE
Vectors Scalars page not working in TAM 210 CBTF Pages

### ISSUE THREAD

**Issue by kelliehalloran** [IllinoisRef/mechref#85]
When I tested out the PrairieLearn reference pages for TAM 210 that are available in the CBTF, I get this error message: 

![Screenshot 2024-09-10 at 3 11 07 PM](https://github.com/user-attachments/assets/6a23d808-f28c-420b-a09f-b3fd4a3a42d2)

I know this is short notice, but is it possible to fix this before the quiz opens tomorrow? 

Thanks!!

**Comment by jcrayb** [comment]
Of course, working on it now.
