### ISSUE TITLE
Add animation and copy full section to Dyn>Contact and rolling

### ISSUE THREAD

**Issue by mopolz2** [IllinoisRef/mechref#93]
There are red comments to where to insert animations.
Blue comment to copy whole section content from https://mechref.engr.illinois.edu/dyn/rko.html

**Comment by jcrayb** [comment]
Let me know if the current page looks good.

**Comment by mopolz2** [comment]
Everything looks good excep the last section "rolling on curved surfaces" which is "Rolling on a 2D curved surface" in the old reference page. 
The animation is not complete, the text below the derivation is a "warning" and should be in a red container, and everything after that is missing (I am guessing there might be a typo somewhere)
Thanks!!!
